name: iOS Pipeline

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: macos-latest  # Use macOS runner
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Ruby
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: '2.7'

    - name: Install CocoaPods
      run: |
        sudo gem install cocoapods
        pod install
    
    - name: Build the iOS app
      run: |
        xcodebuild -workspace hello-world-ios.xcworkspace -scheme hello-world-ios -sdk iphonesimulator -configuration Debug
